
"use strict";
const D=window.PROJECT_DATA;
const colors=['#2458e6','#b45a15','#7742cc','#147a60','#bd3463','#3a7588'];
const fmt=n=>Number(n).toLocaleString('en-GB',{maximumFractionDigits:0});
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const el=id=>document.getElementById(id);
function stats(items){el('stats').innerHTML=items.map(([label,value,note])=>`<div class="stat"><div class="label">${esc(label)}</div><div class="value">${esc(value)}</div><div class="note">${esc(note)}</div></div>`).join('')}
function bars(target,items,formatter=money){const max=Math.max(...items.map(x=>x.value),1);el(target).innerHTML=items.length?items.map((x,i)=>`<div><div class="bar-label"><span>${esc(x.label)}</span><strong>${esc(formatter(x.value))}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(0,x.value/max*100)}%;background:${x.color||colors[0]}"></div></div></div>`).join(''):'<p class="subtle">No sales for this selection.</p>'}
function lineChart(target,rows,series,formatLabel=r=>r.date){const w=760,h=290,p={l:90,r:40,t:20,b:48},max=Math.max(...rows.flatMap(r=>series.map(s=>r[s.key])),1)*1.1;let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(series.map(s=>s.label).join(' and '))} by date">`;
for(let i=0;i<=4;i++){let y=p.t+(h-p.t-p.b)*i/4;svg+=`<line x1="${p.l}" x2="${w-p.r}" y1="${y}" y2="${y}"/><text x="${p.l-10}" y="${y+5}" text-anchor="end">${fmt(max*(1-i/4))}</text>`}
series.forEach(s=>{let pts=rows.map((r,i)=>`${p.l+i/Math.max(1,rows.length-1)*(w-p.l-p.r)},${p.t+(1-r[s.key]/max)*(h-p.t-p.b)}`).join(' ');svg+=`<polyline points="${pts}" fill="none" stroke="${s.color}" stroke-width="2.4"/>`});
const count=Math.min(5,rows.length);for(let j=0;j<count;j++){let i=Math.round(j*(rows.length-1)/Math.max(1,count-1));svg+=`<text x="${p.l+i/Math.max(1,rows.length-1)*(w-p.l-p.r)}" y="${h-13}" text-anchor="middle">${esc(formatLabel(rows[i]))}</text>`}el(target).innerHTML=svg+'</svg>'}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

el('clusters').innerHTML=D.comparisons.map(c=>`<option value="${c.k}">${c.k} segments${c.k===D.selected_k?' · highest silhouette':''}</option>`).join('');el('clusters').value=String(D.selected_k);el('snapshot').textContent=`Snapshot: ${D.snapshot}. ${fmt(D.customers)} customers with known IDs are included. ${fmt(D.audit.missing_customer_rows_retained)} positive-sale rows lack customer IDs and are excluded from segmentation.`;el('comparison').innerHTML=table(['k','Sample silhouette','Seed stability (ARI)','Highest silhouette'],D.comparisons.map(c=>[c.k,c.silhouette.toFixed(3),c.seed_stability_ari.toFixed(3),c.k===D.selected_k?'Yes':'—']));
function assignCustomer(){if(!el('customer').checkValidity()){el('assignment').textContent='—';el('warning').textContent='Enter valid positive values.';return}const values=['recency','frequency','monetary'].map(f=>+el(f).value),k=+el('clusters').value,label=ProjectModel.segment(D,k,values);el('assignment').textContent='Segment '+(label+1);const profile=D.models[String(k)].profiles.find(p=>p.id===label);el('profile-note').textContent=`Typical member: ${fmt(profile.recency)} days since last purchase · ${fmt(profile.frequency)} orders · ${money(profile.monetary)} spend.`;const outside=D.features.filter((f,i)=>values[i]<D.ranges[f][0]||values[i]>D.ranges[f][1]);el('warning').textContent=outside.length?'Outside the observed range: '+outside.join(', ')+'. Nearest segment is an extrapolation.':''}
function updateSegments(){const k=+el('clusters').value,c=D.comparisons.find(x=>x.k===k),profiles=D.models[String(k)].profiles,total=profiles.reduce((s,p)=>s+p.total_sales,0);stats([['Customers',fmt(D.customers),'Known IDs after cleaning'],['Segments',k,'Candidate k = 2 to 6'],['Sample silhouette',c.silhouette.toFixed(3),'Separation, not accuracy'],['Snapshot',D.snapshot,'One day after final sale']]);el('profiles').innerHTML=table(['Segment','Customers','Customer share','Median recency','Median orders','Median spend','Sales share'],profiles.map(p=>['Segment '+(p.id+1),fmt(p.customers),(p.share*100).toFixed(1)+'%',fmt(p.recency)+' days',fmt(p.frequency),money(p.monetary),(p.total_sales/total*100).toFixed(1)+'%']));el('legend').innerHTML=profiles.map(p=>`<span><i class="swatch" style="background:${colors[p.id]}"></i>Segment ${p.id+1}</span>`).join('');const w=740,h=370,l=70,r=24,t=20,b=65,xf=v=>l+Math.log10(v)/Math.log10(250)*(w-l-r),yf=v=>t+(1-Math.log10(Math.max(1,v))/Math.log10(350000))*(h-t-b);let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Sampled customers by number of orders and total spend, colored by segment">`;[1,10,100].forEach(n=>svg+=`<line x1="${xf(n)}" x2="${xf(n)}" y1="${t}" y2="${h-b}"/><text x="${xf(n)}" y="${h-b+25}" text-anchor="middle">${n}</text>`);[10,100,1000,10000,100000].forEach(n=>svg+=`<line x1="${l}" x2="${w-r}" y1="${yf(n)}" y2="${yf(n)}"/><text x="${l-10}" y="${yf(n)+5}" text-anchor="end">${n>=1000?n/1000+'k':n}</text>`);D.points.forEach(p=>{let label=ProjectModel.segment(D,k,[p.recency,p.frequency,p.monetary]);svg+=`<circle cx="${xf(p.frequency)}" cy="${yf(p.monetary)}" r="3" fill="${colors[label]}" opacity=".45"/>`});svg+=`<text x="${w/2}" y="${h-9}" text-anchor="middle">Distinct orders (log scale)</text><text transform="translate(17 ${h/2}) rotate(-90)" text-anchor="middle">Positive spend, GBP (log scale)</text></svg>`;el('scatter').innerHTML=svg;assignCustomer()}
el('clusters').addEventListener('change',updateSegments);el('customer').addEventListener('input',assignCustomer);el('customer').addEventListener('submit',e=>e.preventDefault());updateSegments();
